trigger:
- main

pr:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: Npm@1
  inputs:
    customCommand: 'install'
    workingDir: 'frontend/webbapp'

- task: Npm@1
  inputs:
    customCommand: 'run build'
    workingDir: 'frontend/webbapp'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist' 
    ArtifactName: 'frontend'
    publishLocation: 'Container'

- name: Deploy to Azure Static Web Apps
  uses: azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
