name: CI/CD Workflow

on:
  pull_request:
    types:
      - opened

jobs:
  move-issue-to-review-column:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Move Issue to Review Column for Expo App
        if: ${{ contains(github.event.client_payload.pull_request.base.repo.full_name, 'expo-app') }}
        run: |
          # Your Expo-specific commands to move issue to "Review" column
          # ...

      - name: Move Issue to Review Column for .NET Project
        if: ${{ contains(github.event.client_payload.pull_request.base.repo.full_name, 'dotnet-project') }}
        run: |
          # Your .NET-specific commands to move issue to "Review" column
          # ...

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Move Issue to Review Column (Fallback)
        run: |
          # Extract the pull request number
          PR_NUMBER=$(echo "${{ github.event_name }}_${{ github.event.client_payload.pull_request.number }}")

          # Get the issue number associated with the pull request
          ISSUE_NUMBER=$(gh pr view $PR_NUMBER --json "number" --template "{{.number}}")

          # Move the issue to the "Review" column using GitHub CLI (gh)
          gh issue edit $ISSUE_NUMBER --add-label "Review" --remove-label "In Progress"
